language: 
  - "python"
services: 
  - "postgresql"
python:
  - "2.7"
env:
  - PG_USER="postgres"
  - PG_PASSWORD=""
  - PG_DBNAME="postgres"
install:
  - "pip install . --use-mirrors"
  - "pip install -r tests/requirements.txt --use-mirrors"
  - "pip install coveralls -U --use-mirrors"
before_script:
  # Creating the database and adding the hstore extension
  - "psql -c 'DROP DATABASE IF EXISTS $PG_DBNAME;' -U $PG_USER"
  - "psql -c 'create database $PG_DBNAME;' -U $PG_USER"
  - "psql -d $PG_DBNAME -c 'create extension hstore;' -U $PG_USER"

  # Changing the DATABASES settings configs
  - "cp tests/local_settings.sample tests/local_settings.py"
script:
  - "coverage run runtests.py"
after_success:
  - "coverage html"
  - "coveralls"